# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

s4:
- source:
    tableName: acdoca
  target:
    tags: [sap, s4, finance, hourly]
    clusterDetails:
      columns: [rclnt, rbukrs]
- source:
    tableName: acdocu
  target:
    tags: [sap, s4, finance, hourly]
- source:
    tableName: ckmlcr
  target:
    tags: [sap, s4, finance, controlling, daily]
- source:
    tableName: ckmlhd
  target:
    tags: [sap, s4, finance, controlling, daily]
- source:
    tableName: finsc_ld_cmp
  target:
    tags: [sap, s4, finance, daily]
- source:
    tableName: finsc_ledger
  target:
    tags: [sap, s4, finance, yearly]
- source:
    tableName: finsc_ledger_rep
  target:
    tags: [sap, s4, finance, daily]
- source:
    tableName: finsc_ledger_t
  target:
    tags: [sap, s4, finance, yearly]
- source:
    tableName: fincs_ref_vers_r
  target:
    tags: [sap, s4, finance, yearly]
- source:
    tableName: hrrp_directory
  target:
    tags: [sap, s4, hr, monthly]
- source:
    tableName: hrrp_node
  target:
    tags: [sap, s4, hr, monthly]
- source:
    tableName: hrrp_nodet
  target:
    tags: [sap, s4, hr, monthly]
- source:
    tableName: matdoc
  target:
    tags: [sap, s4, logistics, material, hourly]
- source:
    tableName: prcd_elements
  target:
    tags: [sap, s4, sales, pricing, hourly]
- source:
    tableName: sethanahier0101
  target:
    tags: [sap, s4, sets, monthly]
- source:
    tableName: sethanahier0106
  target:
    tags: [sap, s4, sets, monthly]
- source:
    tableName: tf200
  target:
    tags: [sap, s4, finance, yearly]
- source:
    tableName: tf201
  target:
    tags: [sap, s4, finance, yearly]
ecc:
- source:
    tableName: faglflexa
  target:
    tags: [sap, ecc, finance, hourly]
- source:
    tableName: konv
  target:
    tags: [sap, ecc, sales, pricing, daily]
    clusterDetails:
      columns: [stunr]
    partitionDetails:
      column: kdatu
      partitionType: time
      timeGrain: day
- source:
    tableName: mseg
  target:
    tags: [sap, ecc, logistics, material, hourly]
- source:
    tableName: msfd
  target:
    tags: [sap, ecc, logistics, forecast, weekly]
- source:
    tableName: vbuk
  target:
    tags: [sap, ecc, sales, status, hourly]
- source:
    tableName: vbup
  target:
    tags: [sap, ecc, sales, status, hourly]
- source:
    tableName: bsik
  target:
    tags: [sap, ecc, finance, hourly]
- source:
    tableName: bsak
  target:
    tags: [sap, ecc, finance, hourly]
- source:
    tableName: bsid
  target:
    tags: [sap, ecc, finance, hourly]
- source:
    tableName: bsad
  target:
    tags: [sap, ecc, finance, hourly]
common:
- source:
    tableName: adr6
  target:
    tags: [sap, common, masterdata, address, daily]
- source:
    tableName: adrc
  target:
    tags: [sap, common, masterdata, address, daily]
- source:
    tableName: adrct
  target:
    tags: [sap, common, masterdata, address, daily]
- source:
    tableName: anla
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: ankt
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: anlh
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: anlb
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: t093b
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: t093t
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: t090nat
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: t093c
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: anlz
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: t095t
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: t098t
  target:
    tags: [sap, common, finance, assets, hourly]
- source:
    tableName: afko
  target:
    tags: [sap, common, production, hourly]
- source:
    tableName: afpo
  target:
    tags: [sap, common, production, hourly]
- source:
    tableName: aufk
  target:
    tags: [sap, common, production, hourly]
- source:
    tableName: bkpf
  target:
    tags: [sap, common, finance, hourly]
    clusterDetails:
      columns: [bukrs, gjahr]
    partitionDetails:
      column: budat
      partitionType: time
      timeGrain: day
- source:
    tableName: bseg
  target:
    tags: [sap, common, finance, hourly]
    clusterDetails:
      columns: [mandt, bukrs, gjahr]
- source:
    tableName: but000
  target:
    tags: [sap, common, masterdata, bp, daily]
- source:
    tableName: but020
  target:
    tags: [sap, common, masterdata, bp, daily]
- source:
    tableName: but0bk
  target:
    tags: [sap, common, masterdata, bp, daily]
- source:
    tableName: cepc
  target:
    tags: [sap, common, finance, controlling, daily]
- source:
    tableName: cepct
  target:
    tags: [sap, common, finance, controlling, daily]
- source:
    tableName: csks
  target:
    tags: [sap, common, finance, controlling, daily]
- source:
    tableName: cskt
  target:
    tags: [sap, common, finance, controlling, daily]
- source:
    tableName: ekbe
  target:
    tags: [sap, common, logistics, purchasing, hourly]
    clusterDetails:
      columns: [mandt, vgabe, ebeln, bwart]
    partitionDetails:
      column: budat
      partitionType: time
      timeGrain: day
- source:
    tableName: ekes
  target:
    tags: [sap, common, logistics, purchasing, hourly]
- source:
    tableName: eket
  target:
    tags: [sap, common, logistics, purchasing, hourly]
    clusterDetails:
      columns: [mandt, ebeln]
    partitionDetails:
      column: eindt
      partitionType: time
      timeGrain: day
- source:
    tableName: ekkn
  target:
    tags: [sap, common, logistics, purchasing, hourly]
- source:
    tableName: ekko
  target:
    tags: [sap, common, logistics, purchasing, hourly]
    clusterDetails:
      columns: [mandt, ebeln]
    partitionDetails:
      column: bedat
      partitionType: time
      timeGrain: day
- source:
    tableName: ekpo
  target:
    tags: [sap, common, logistics, purchasing, hourly]
    clusterDetails:
      columns: [mandt, ebeln]
    partitionDetails:
      column: aedat
      partitionType: time
      timeGrain: day
- source:
    tableName: fagl_011pc
  target:
    tags: [sap, common, finance, monthly]
- source:
    tableName: fagl_011qt
  target:
    tags: [sap, common, finance, monthly]
- source:
    tableName: fagl_011zc
  target:
    tags: [sap, common, finance, monthly]
- source:
    tableName: jest
  target:
    tags: [sap, common, status, daily]
- source:
    tableName: kna1
  target:
    tags: [sap, common, masterdata, customer, daily]
- source:
    tableName: lfa1
  target:
    tags: [sap, common, masterdata, vendor, daily]
- source:
    tableName: likp
  target:
    tags: [sap, common, logistics, delivery, hourly]
    clusterDetails:
      columns: [vkorg]
    partitionDetails:
      column: erdat
      partitionType: time
      timeGrain: month
- source:
    tableName: lips
  target:
    tags: [sap, common, logistics, delivery, hourly]
    partitionDetails:
      column: erdat
      partitionType: time
      timeGrain: month
- source:
    tableName: makt
  target:
    tags: [sap, common, masterdata, material, daily]
    clusterDetails:
      columns: [spras]
- source:
    tableName: mara
  target:
    tags: [sap, common, masterdata, material, daily] 
- source:
    tableName: marc
  target:
    tags: [sap, common, masterdata, material, hourly]
- source:
    tableName: mard
  target:
    tags: [sap, common, masterdata, material, hourly]
- source:
    tableName: mast
  target:
    tags: [sap, common, production, bom, monthly]
- source:
    tableName: mbew
  target:
    tags: [sap, common, logistics, valuation, daily]
- source:
    tableName: mbewh
  target:
    tags: [sap, common, logistics, valuation, daily]
- source:
    tableName: mch1
  target:
    tags: [sap, common, logistics, batch, daily]
- source:
    tableName: mcha
  target:
    tags: [sap, common, logistics, batch, daily]
- source:
    tableName: mchb
  target:
    tags: [sap, common, logistics, batch, stock, daily]
- source:
    tableName: mkol
  target:
    tags: [sap, common, logistics, stock, weekly]
- source:
    tableName: mska
  target:
    tags: [sap, common, logistics, stock, weekly]
- source:
    tableName: msku
  target:
    tags: [sap, common, logistics, stock, weekly]
- source:
    tableName: mslb
  target:
    tags: [sap, common, logistics, stock, weekly]
- source:
    tableName: proj
  target:
    tags: [sap, common, projects, hourly]
- source:
    tableName: prps
  target:
    tags: [sap, common, projects, hourly]
- source:
    tableName: prte
  target:
    tags: [sap, common, projects, hourly]
- source:
    tableName: prhi
  target:
    tags: [sap, common, projects, hourly]
- source:
    tableName: rpsco
  target:
    tags: [sap, common, projects, finance, daily]
- source:
    tableName: rbco
  target:
    tags: [sap, common, logistics, invoice, hourly]
- source:
    tableName: rbkp
  target:
    tags: [sap, common, logistics, invoice, hourly]
- source:
    tableName: rseg
  target:
    tags: [sap, common, logistics, invoice, hourly]
- source:
    tableName: setheader
  target:
    tags: [sap, common, sets, monthly]
- source:
    tableName: setheadert
  target:
    tags: [sap, common, sets, monthly]
- source:
    tableName: setleaf
  target:
    tags: [sap, common, sets, monthly]
- source:
    tableName: setnode
  target:
    tags: [sap, common, sets, monthly]
- source:
    tableName: ska1
  target:
    tags: [sap, common, finance, gl, daily]
- source:
    tableName: skat
  target:
    tags: [sap, common, finance, gl, daily]
- source:
    tableName: stas
  target:
    tags: [sap, common, production, bom, monthly]
- source:
    tableName: stko
  target:
    tags: [sap, common, production, bom, monthly]
- source:
    tableName: stpo
  target:
    tags: [sap, common, production, bom, monthly]
- source:
    tableName: t001
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t001k
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t001l
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t001w
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t002
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t002t
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t005
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: t005k
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: t005s
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: t005u
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: t005t
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: t006
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: t006a
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t006t
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t009
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t009b
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t023
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t023t
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t024
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t024e
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t134
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t134t
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t148t
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t156
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t156t
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t157e
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t161
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t161t
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t179
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t179t
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t881
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: t881t
  target:
    tags: [sap, common, configuration, once]
- source:
    tableName: tcurc
  target:
    tags: [sap, common, configuration, currency, once]
- source:
    tableName: tcurf
  target:
    tags: [sap, common, configuration, currency, once]
- source:
    tableName: tcurr
  target:
    tags: [sap, common, configuration, currency, daily]
- source:
    tableName: tcurt
  target:
    tags: [sap, common, configuration, currency, daily]
- source:
    tableName: tcurx
  target:
    tags: [sap, common, configuration, currency, daily]
- source:
    tableName: tj02t
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: tka02
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: tka01
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: cskb
  target:
    tags: [sap, common, finance, controlling, daily]
- source:
    tableName: csku
  target:
    tags: [sap, common, finance, controlling, daily]
- source:
    tableName: tspa
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: tspat
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: tvarvc
  target:
    tags: [sap, common, configuration, daily]
- source:
    tableName: tvfst
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: tvko
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: tvkot
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: tvlst
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: tvtw
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: tvtwt
  target:
    tags: [sap, common, configuration, yearly]
- source:
    tableName: vbak
  target:
    tags: [sap, common, sales, hourly]
    clusterDetails:
      columns: [vkorg]
    partitionDetails:
      column: audat
      partitionType: time
      timeGrain: day
- source:
    tableName: vbap
  target:
    tags: [sap, common, sales, hourly]
    clusterDetails:
      columns: [werks, lgort]
- source:
    tableName: vbep
  target:
    tags: [sap, common, sales, hourly]
- source:
    tableName: vbfa
  target:
    tags: [sap, common, sales, hourly]
- source:
    tableName: vbpa
  target:
    tags: [sap, common, sales, hourly]
- source:
    tableName: vbrk
  target:
    tags: [sap, common, sales, billing, hourly]
- source:
    tableName: vbrp
  target:
    tags: [sap, common, sales, billing, hourly]
- source:
    tableName: wbrk
  target:
    tags: [sap, common, sales, billing, hourly]
- source:
    tableName: wbrp
  target:
    tags: [sap, common, sales, billing, hourly]
- source:
    tableName: wcocoh
  target:
    tags: [sap, common, sales, contract, daily]
- source:
    tableName: wcocoi
  target:
    tags: [sap, common, sales, contract, daily]
- source:
    tableName: wb2_d_settl_cal
  target:
    tags: [sap, common, sales, rebates, daily]
- source:
    tableName: wb2_d_bvdetail
  target:
    tags: [sap, common, sales, settlement, daily]